name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    strategy:
      matrix:
        ui: [console, full]
        os: [ubuntu-latest, windows-latest]
        # Remember to update the upload step below with latest Go version
        go-version: [ '1.20', '1.21', '1.22', '1.23' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Show environment info
        run: |
          echo "OS: $RUNNER_OS"
          echo "Go version: ${{ matrix.go-version }}"
          echo "UI: ${{ matrix.ui }}"
          echo "Matrix: os=${{ matrix.os }}, go-version=${{ matrix.go-version }}, ui=${{ matrix.ui }}"

      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Install C compiler and OpenGL (Linux)
        if: matrix.ui == 'full' && runner.os == 'Linux'
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y build-essential libgl1-mesa-dev xorg-dev

      - name: Install C compiler (Windows)
        if: matrix.ui == 'full' && runner.os == 'Windows'
        run: choco install mingw -y

      - name: Run golangci-lint # Linux-only for speed
        if: runner.os == 'Linux'
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: ${{ matrix.ui == 'console' && '--build-tags=console --timeout=5m' || '--timeout=5m' }}

      - name: Vet # Linux-only for speed
        if: runner.os == 'Linux'
        shell: bash
        run: |
          if [ "${{ matrix.ui }}" = "console" ]; then
            go vet -tags console ./...
          else
            mage vet
          fi

      - name: Test
        shell: bash
        run: |
          if [ "${{ matrix.ui }}" = "console" ]; then
            go test -tags console ./...
          else
            mage test
          fi

      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.ui }}" = "console" ]; then
            mage buildConsole
          else
            mage build
          fi

      - name: Upload binaries
        if: matrix.go-version == '1.23' && matrix.ui == 'full'
        uses: actions/upload-artifact@v4
        with:
          name: tetris-${{ runner.os }}
          path: |
            tetris*
            *.exe
          retention-days: 2
